# Generated by Django 4.2 on 2023-04-05 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='someonesPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('attack1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack1', to='web.attack')),
                ('attack2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack2', to='web.attack')),
                ('attack3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack3', to='web.attack')),
                ('attack4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack4', to='web.attack')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.item')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.pokemon')),
                ('tera_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.type')),
            ],
        ),
        migrations.CreateModel(
            name='PokePaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pokepaste_code', models.CharField(max_length=100)),
                ('pokemon1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon1', to='web.someonespokemon')),
                ('pokemon2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon2', to='web.someonespokemon')),
                ('pokemon3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon3', to='web.someonespokemon')),
                ('pokemon4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon4', to='web.someonespokemon')),
                ('pokemon5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon5', to='web.someonespokemon')),
                ('pokemon6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon6', to='web.someonespokemon')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type1', to='web.type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type2', to='web.type'),
        ),
        migrations.AddField(
            model_name='attack',
            name='type1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.type'),
        ),
    ]
