# Generated by Django 4.2 on 2023-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='img_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
